basePath: /api/v1
consumes:
- application/json
definitions:
  AnalyzeRequest:
    description: AnalyzeRequest represents the request to the analyze service via
      GRPC
    properties:
      analyzeTemplate:
        $ref: '#/definitions/AnalyzeTemplate'
      text:
        description: The text to analyze
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnalyzeResult:
    description: AnalyzeResult represents the Analyze service findings
    properties:
      field:
        $ref: '#/definitions/FieldTypes'
      location:
        $ref: '#/definitions/Location'
      score:
        description: The score of the result
        format: float
        type: number
        x-go-name: Score
      text:
        description: The sensitive text result
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnalyzeTemplate:
    properties:
      allFields:
        description: Optional flag to request all existing fields. if true, "fields"
          must be empty.
        type: boolean
        x-go-name: AllFields
      createTime:
        description: Template Creation date
        type: string
        x-go-name: CreateTime
      description:
        description: Template description
        type: string
        x-go-name: Description
      fields:
        description: Array of the fields to analyze
        items:
          $ref: '#/definitions/FieldTypes'
        type: array
        x-go-name: Fields
      language:
        description: Language code, in ISO-639 format, https://en.wikipedia.org/wiki/ISO_639-1
        type: string
        x-go-name: Language
      modifiedTime:
        description: Template modification date
        type: string
        x-go-name: ModifiedTime
      resultsScoreThreshold:
        description: Threshold to filter results based on their score
        format: float
        type: number
        x-go-name: ResultsScoreThreshold
    title: AnalyzeTemplate represents the template definition of the Analyze service-
      for analyzing sensitive text.
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnonymizeImageRequest:
    description: AnonymizeRequest represents the request to the anonymize service
      via GRPC
    properties:
      analyzeResults:
        description: The analyze result containing the field type and location of
          the sensetive data to be anonymized.
        items:
          $ref: '#/definitions/AnalyzeResult'
        type: array
        x-go-name: AnalyzeResults
      detectionType:
        $ref: '#/definitions/DetectionTypeEnum'
      image:
        $ref: '#/definitions/Image'
      template:
        $ref: '#/definitions/AnonymizeImageTemplate'
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnonymizeImageResponse:
    description: AnonymizeResponse represents the anonymize service response
    properties:
      image:
        $ref: '#/definitions/Image'
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnonymizeImageTemplate:
    description: AnonymizeImageTemplate represents the template definition of the
      Anonymize image service
    properties:
      createTime:
        description: Template Creation date
        type: string
        x-go-name: CreateTime
      description:
        description: Template description
        type: string
        x-go-name: Description
      fieldTypeGraphics:
        description: FieldTypeGraphic represents the graphics for an array of fields
          types
        items:
          $ref: '#/definitions/FieldTypeGraphic'
        type: array
        x-go-name: FieldTypeGraphics
      modifiedTime:
        description: Template modification date
        type: string
        x-go-name: ModifiedTime
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnonymizeRequest:
    description: AnonymizeRequest represents the request to the anonymize service
      via GRPC
    properties:
      analyzeResults:
        description: The analyze result containing the field type and location of
          the sensetive data to be anonymized.
        items:
          $ref: '#/definitions/AnalyzeResult'
        type: array
        x-go-name: AnalyzeResults
      template:
        $ref: '#/definitions/AnonymizeTemplate'
      text:
        description: The text to anonymize
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnonymizeResponse:
    description: AnonymizeResponse represents the anonymize service response
    properties:
      text:
        description: The text with the senstive fields anonymized
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  AnonymizeTemplate:
    description: AnonymizeTemplate represents the template definition of the Anonymize
      service for anonymizying the sensitive data
    properties:
      createTime:
        description: Template Creation date
        type: string
        x-go-name: CreateTime
      defaultTransformation:
        $ref: '#/definitions/Transformation'
      description:
        description: Template description
        type: string
        x-go-name: Description
      fieldTypeTransformations:
        description: FieldTypeTransformation represents the transformation for an
          array of fields types
        items:
          $ref: '#/definitions/FieldTypeTransformation'
        type: array
        x-go-name: FieldTypeTransformations
      modifiedTime:
        description: Template modification date
        type: string
        x-go-name: ModifiedTime
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  Boundingbox:
    description: Define an extracted bounding box text/image from images
    properties:
      endPosition:
        description: End position of char in text
        format: int32
        type: integer
        x-go-name: EndPosition
      height:
        description: Height of BBox
        format: float
        type: number
        x-go-name: Height
      startPosition:
        description: Start position of char in text
        format: int32
        type: integer
        x-go-name: StartPosition
      text:
        description: Text in BBox
        type: string
        x-go-name: Text
      width:
        description: Width of BBox
        format: float
        type: number
        x-go-name: Width
      xLocation:
        description: Pixel X location of BBox
        format: float
        type: number
        x-go-name: XLocation
      yLocation:
        description: Pixel Y location of BBox
        format: float
        type: number
        x-go-name: YLocation
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  DetectionTypeEnum:
    description: Anonymize image detection type
    format: int32
    type: integer
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  FPEValue:
    properties:
      decrypt:
        description: true to decrypt value
        type: boolean
        x-go-name: Decrypt
      key:
        description: base64 encoded 128, 192, 256 size key
        type: string
        x-go-name: Key
      tweak:
        description: base64 encoded tweak. Size must be below 8
        type: string
        x-go-name: Tweak
    title: Encrypt the given value with FFI alogrithm to presereve detected value
      size.
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  FieldTypeGraphic:
    description: FieldTypeGraphic represents the graphics for an array of fields types
    properties:
      fields:
        description: The array of field types
        items:
          $ref: '#/definitions/FieldTypes'
        type: array
        x-go-name: Fields
      graphic:
        $ref: '#/definitions/Graphic'
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  FieldTypeTransformation:
    description: FieldTypeTransformation represents the transformation for an array
      of fields types
    properties:
      fields:
        description: The array of field types
        items:
          $ref: '#/definitions/FieldTypes'
        type: array
        x-go-name: Fields
      transformation:
        $ref: '#/definitions/Transformation'
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  FieldTypes:
    description: FieldType strucy
    properties:
      minScore:
        description: The minScore will filter results which has lower certainty than
          the provided value.
        type: string
        x-go-name: MinScore
      name:
        description: Field type name
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  FillColorValue:
    description: Fill the bbox with a color
    properties:
      blue:
        description: 0 - 255
        format: double
        type: number
        x-go-name: Blue
      green:
        description: 0 - 255
        format: double
        type: number
        x-go-name: Green
      red:
        description: 0 - 255
        format: double
        type: number
        x-go-name: Red
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  Graphic:
    description: Graphic represents how the sensitive content will be transforms
    properties:
      fillColorValue:
        $ref: '#/definitions/FillColorValue'
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  HashValue:
    title: Uses cryptographich hash on the given value with SHA-256 hash.
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  Image:
    description: Define an image with extracted bounded boxes of text/image
    properties:
      Boundingboxes:
        description: Array of Boundingbox
        items:
          $ref: '#/definitions/Boundingbox'
        type: array
      data:
        description: The image data in bytes
        items:
          format: uint8
          type: integer
        type: array
        x-go-name: Data
      imageType:
        description: The image type JPEG/PNG/TIFF
        type: string
        x-go-name: ImageType
      text:
        description: Image Text
        type: string
        x-go-name: Text
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  Location:
    description: The location in the text of the finding
    properties:
      end:
        description: The location end
        format: int32
        type: integer
        x-go-name: End
      length:
        description: The location length
        format: int32
        type: integer
        x-go-name: Length
      start:
        description: The location start
        format: int32
        type: integer
        x-go-name: Start
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  MaskValue:
    description: |-
      For example: my credit card number is 4961-2765-5327-5913
      maskingCharacter: '*', chars to mask: 9, fromEnd: true
      Will output:  my credit card number is 4961-2765-*********
    properties:
      charsToMask:
        description: number of chars to mask
        format: int32
        type: integer
        x-go-name: CharsToMask
      fromEnd:
        description: Should start masking from end
        type: boolean
        x-go-name: FromEnd
      maskingCharacter:
        description: the masking char
        type: string
        x-go-name: MaskingCharacter
    title: Mask the given value with the selected characters.
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  RedactValue:
    title: Redacts the given value. For example We met in Seattle would change to
      'We me in '.
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  ReplaceValue:
    description: |-
      For example: We met in Seattle.
      new value: <Location>
      replace to 'We met in <Location>'
    properties:
      newValue:
        description: The value to replace
        type: string
        x-go-name: NewValue
    title: Replace the value with the given new value.
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
  Transformation:
    description: Transformation represents the transformation types - how the sensitive
      text will change
    properties:
      fPEValue:
        $ref: '#/definitions/FPEValue'
      hashValue:
        $ref: '#/definitions/HashValue'
      maskValue:
        $ref: '#/definitions/MaskValue'
      redactValue:
        $ref: '#/definitions/RedactValue'
      replaceValue:
        $ref: '#/definitions/ReplaceValue'
    type: object
    x-go-package: github.com/microsoft/presidio/vendor/github.com/Microsoft/presidio-genproto/golang
host: some-url.com
info:
  description: Documentation of our Presidio API.
  title: Presidio.
  version: 1.0.0
paths:
  /projects/{projectId}/analyze:
    post:
      description: Analyze text
      operationId: analyzeRequest
      parameters:
      - description: The request body
        in: body
        name: Body
        schema:
          $ref: '#/definitions/AnalyzeRequest'
      - format: int64
        in: path
        name: projectId
        required: true
        type: integer
        x-go-name: ProjectId
      responses:
        "200":
          $ref: '#/responses/analyzeResponse'
      tags:
      - analyze
  /projects/{projectId}/anonymize:
    post:
      description: Anonymize text
      operationId: anonymizeRequest
      parameters:
      - description: The request body
        in: body
        name: Body
        schema:
          $ref: '#/definitions/AnonymizeRequest'
      - format: int64
        in: path
        name: projectId
        required: true
        type: integer
        x-go-name: ProjectId
      responses:
        "200":
          $ref: '#/responses/anonymizeResponse'
      tags:
      - anonymize
  /projects/{projectId}/anonymize-image:
    post:
      description: Anonymize image
      operationId: anonymizeImageRequest
      parameters:
      - description: The request body
        in: body
        name: Body
        schema:
          $ref: '#/definitions/AnonymizeImageRequest'
      - format: int64
        in: path
        name: projectId
        required: true
        type: integer
        x-go-name: ProjectId
      responses:
        "200":
          $ref: '#/responses/anonymizeImageResponse'
      tags:
      - anonymize
produces:
- application/json
responses:
  analyzeResponse:
    description: A response includes a list of recognized fields in the text to be
      anonymized.
    schema:
      items:
        $ref: '#/definitions/AnalyzeResult'
      type: array
  anonymizeImageResponse:
    description: A response includes anonymized image.
    schema:
      $ref: '#/definitions/AnonymizeImageResponse'
  anonymizeResponse:
    description: A response includes anonymized text.
    schema:
      $ref: '#/definitions/AnonymizeResponse'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
